### ISSUE TITLE
Missing comma in slick.core.js (Version 2.4.27 patch)

### ISSUE THREAD

**Issue by snowkrebs** [bokeh/SlickGrid#4]
Seems to be missing a comma here?

https://github.com/bokeh/SlickGrid/blob/bokeh%402.4.27/slick.core.js#L660

With current bokehjs version:

@bokeh/bokehjs `2.1.1`

the slickgrid dependency is: 

`"@bokeh/slickgrid": "^2.3.23"`

which is causing some problem with build

<img width="596" alt="Screenshot at Jul 29 19-38-44" src="https://user-images.githubusercontent.com/6148644/88795792-2bb7ec80-d1d3-11ea-8d0f-3390b694ebe4.png">

cc @mattpap

**Comment by mattpap** [comment]
> @bokeh/bokehjs 2.1.1
> "@bokeh/slickgrid": "^2.3.23"

I would be sure, given those dependencies, you shouldn't be seeing this bug, but in `bokehjs/package.json` we have:

```json
"@bokeh/slickgrid": "^2.3.23"
```
which allows this, pulling in the most recent and incompatible version of slickgrid. It would have been better if we used `~` instead of `^`.

As to the missing comma, bokehjs build system fixed this when post-processing modules, but didn't let us know about the issue.

**Comment by mattpap** [comment]
I published `2.4.27-1` fixing this. We will need to consider a stricter versioning policy in bokehjs.

**Comment by snowkrebs** [comment]
> > @bokeh/bokehjs 2.1.1
> > "@bokeh/slickgrid": "^2.3.23"
> 
> I would be sure, given those dependencies, you shouldn't be seeing this bug, but in `bokehjs/package.json` we have:
> 
> ```json
> "@bokeh/slickgrid": "^2.3.23"
> ```
> 
> which allows this, pulling in the most recent and incompatible version of slickgrid. It would have been better if we used `~` instead of `^`.
> 
> As to the missing comma, bokehjs build system fixed this when post-processing modules, but didn't let us know about the issue.


Gotcha, thanks for the quick response!


by the way I was installing with without specifying any slickgrid version
```
yarn add @bokeh/bokehjs
```
